#!/bin/sh
cd frontend

export NODE_ENV=${ENV}
export VITE_BACKEND_URL=${BACKEND_URL}
export VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
export VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
export VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
export VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
export VITE_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
export VITE_FIREBASE_APP_ID=${FIREBASE_APP_ID}
export VITE_FIREBASE_MEASUREMENT_ID=${FIREBASE_MEASUREMENT_ID}

npm run dev